backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
site_url: https://eduardogc.dev/blog
display_url: https://eduardogc.dev/blog
collections:
  - label: "Blog em português"
    name: "posts_portugues"
    folder: "content/pt-br"
    create: true
    filter: {field: "language", value: "pt-br"}
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "pt-br"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Post author", name: "author", widget: "select", options: ["Eduardo GC"]}
      - {label: "Content", name: "body", widget: "markdown"}
  - label: "Blog in English"
    name: "english_posts"
    folder: "content/en"
    create: true
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "pt-br"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Post author", name: "author", widget: "select", options: ["Eduardo GC"]}
      - {label: "Content", name: "body", widget: "markdown"}